CREATE TABLE CUSTOMER (
CONTACT_ID SERIAL NOT NULL,
FIRST_NAME VARCHAR(500),
LAST_NAME VARCHAR(500),
EMAIL_ADDRESS VARCHAR(500),
CREATED_BY VARCHAR(500),
CREATED_DATE DATE,
UPDATED_BY VARCHAR(500),
UPDATED_DATE DATE,
IS_ACTIVE VARCHAR(1),
PRIMARY KEY(CONTACT_ID) );

--insert into CUSTOMER (
--FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE,IS_ACTIVE)
--values ('Rajesh', 'Kumar', 'rajesh.kumar@trantorinc.com', 'E00997', null, 'E00997', null, 'Y');
--insert into CUSTOMER (
--FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE,IS_ACTIVE)
--values ('Ishu', 'Thakur', 'ishu.thakur@trantorinc.com', 'E01801', null, 'E01801', null, 'Y');
--insert into CUSTOMER (
--FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE,IS_ACTIVE)
--values ('Klm', 'Kumar', 'klm.kumar@trantorinc.com', 'E00998', null, 'E00998', null, 'Y');




CREATE TABLE MOBILE (
MOBILE_ID SERIAL NOT NULL,
MOBILE_NUMBER VARCHAR(500),
COUNTRY_CODE VARCHAR(500),
TYPE VARCHAR(500),
CREATED_BY VARCHAR(500),
CREATED_DATE DATE,
UPDATED_BY VARCHAR(500),
UPDATED_DATE DATE,
CONTACT_ID INTEGER,
PRIMARY KEY(MOBILE_ID),
FOREIGN KEY (CONTACT_ID) REFERENCES CUSTOMER(CONTACT_ID) );



--insert into MOBILE (
--MOBILE_NUMBER,COUNTRY_CODE,TYPE,CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, CONTACT_ID)
--values('9828344692', '+91', 'Home', 'E00997', null, 'E00997', null, 1);
--insert into MOBILE (
--MOBILE_NUMBER,COUNTRY_CODE,TYPE,CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, CONTACT_ID)
--values('9988629870', '+91', 'Home', 'E01801', null, 'E01801', null, 2);
--insert into MOBILE (
--MOBILE_NUMBER,COUNTRY_CODE,TYPE,CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, CONTACT_ID)
--values('896892178', '+91', 'Work', 'E00998', null, 'E00998', null, 3);


--SELECT * INTO CUSTOMER FROM OPENROWSET('Microsoft.Jet.OLEDB.4.0',
--'Excel 8.0;Database=C:\\Users\\ishu.thakur\\Downloads\\AddressBook_2022-04-05_12_56_21.xlsx', [ADDRESS_BOOK$])

BULK INSERT address_book.customer
	FROM 'C:/Users/ishu.thakur/Downloads/AddressBook_2022-04-05_12_56_21.csv'
	WITH
	(
		FIELDTERMINATOR=',',
		ROWTERMINATOR='\n'
	)